language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t prometheousjames/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true prometheousjames/docker-react npm run test